package uz.lebellion.submission.storage

/**
 * Abstracts photo blob storage behind an opaque key, so the local-disk impl can be swapped for an
 * S3-compatible one later without touching callers. The key is generated by the store, never by the
 * caller, and is unpredictable.
 */
interface StorageService {
    /** Persist [bytes] and return a fresh, unpredictable storage key. */
    fun store(bytes: ByteArray, contentType: String): String

    /** Load the bytes for [storageKey], or throw if it does not exist. */
    fun load(storageKey: String): ByteArray
}
